---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Get the API token if not have it
      # NOTE: include_tasks is dynamic include
      include_tasks: tasks/pve_get_token.yaml  
      when: token is not defined
    - name: Delete VM
      uri:
        url: "{{ lookup('env', 'PVE_API_ENDPOINT') }}/api2/json/nodes/{{ node }}/qemu/{{ vmid }}"
        method: DELETE
        headers:
          Cookie: PVEAuthCookie={{ token.data.ticket }}
          CSRFPreventionToken: "{{ token.data.CSRFPreventionToken }}"
        status_code: 200
